on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: allentestcr.azurecr.io
        username: ${{ secrets.acr_allentestcr_username }}
        password: ${{ secrets.acr_allentestcr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/shanghai/2019" -f  "shanghai/2019/Dockerfile" -t allentestcr.azurecr.io/allen18test:${{ github.sha }} --label dockerfile-path=shanghai/2019/Dockerfile
        docker push allentestcr.azurecr.io/allen18test:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_allen18test_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep contributor | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace contributor`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: contributor
        container-registry-url: allentestcr.azurecr.io
        container-registry-username: ${{ secrets.acr_allentestcr_username }}
        container-registry-password: ${{ secrets.acr_allentestcr_password }}
        secret-name: allen18testdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: contributor
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          allentestcr.azurecr.io/allen18test:${{ github.sha }}
        imagepullsecrets: |
          allen18testdockerauth
